version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3"

# declare the Python requirements required to build docco
 python:
   install:
     - requirements: requirements.txt
